name: prueba13
services:
  postgresql:
    image: postgres:15.3
    volumes:
      - ./bd/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=prueba13
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - 5432:5432
